from enum import Enum
from typing import List


class Keyword(str, Enum):
    """Represents a keyword."""

    # evergreen
    Deathtouch = "Deathtouch"
    Defender = "Defender"
    DoubleStrike = "Double Strike"
    Enchant = "Enchant"
    Equip = "Equip"
    FirstStrike = "First Strike"
    Flash = "Flash"
    Flying = "Flying"
    Haste = "Haste"
    Hexproof = "Hexproof"
    Indestructible = "Indestructible"
    Lifelink = "Lifelink"
    Menace = "Menace"
    Prowess = "Prowess"
    Reach = "Reach"
    Trample = "Trample"
    Vigilance = "Vigilance"

    # other
    Absorb = "Absorb"
    Affinity = "Affinity"
    Amplify = "Amplify"
    Annihilator = "Annihilator"
    AuraSwap = "Aura Swap"
    Awaken = "Awaken"
    Banding = "Banding"
    BattleCry = "Battle Cry"
    Bestow = "Bestow"
    Bloodthirst = "Bloodthirst"
    Bushido = "Bushido"
    Buyback = "Buyback"
    Cascade = "Cascade"
    Champion = "Champion"
    Changeling = "Changeling"
    Cipher = "Cipher"
    Conspire = "Conspire"
    Convoke = "Convoke"
    CumulativeUpkeep = "Cumulative Upkeep"
    Cycling = "Cycling"
    Dash = "Dash"
    Delve = "Delve"
    Dethrone = "Dethrone"
    Devoid = "Devoid"
    Devour = "Devour"
    Dredge = "Dredge"
    Echo = "Echo"
    Entwine = "Entwine"
    Epic = "Epic"
    Evoke = "Evoke"
    Evolve = "Evolve"
    Exalted = "Exalted"
    Exploit = "Exploit"
    Explore = "Explore"
    Extort = "Extort"
    Fading = "Fading"
    Fear = "Fear"
    Flanking = "Flanking"
    Flashback = "Flashback"
    Forecast = "Forecast"
    Fortify = "Fortify"
    Frenzy = "Frenzy"
    Fuse = "Fuse"
    Graft = "Graft"
    Gravestorm = "Gravestorm"
    Haunt = "Haunt"
    HiddenAgenda = "Hidden Agenda"
    Hideaway = "Hideaway"
    Horsemanship = "Horsemanship"
    Infect = "Infect"
    Ingest = "Ingest"
    Intimidate = "Intimidate"
    Kicker = "Kicker"
    Landhome = "Landhome"
    Landwalk = "Landwalk"
    LevelUp = "Level Up"
    LivingWeapon = "Living Weapon"
    Madness = "Madness"
    Megamorph = "Megamorph"
    Miracle = "Miracle"
    Modular = "Modular"
    Morph = "Morph"
    Myriad = "Myriad"
    Ninjutsu = "Ninjutsu"
    Offering = "Offering"
    Outlast = "Outlast"
    Overload = "Overload"
    Persist = "Persist"
    Phasing = "Phasing"
    Poisonous = "Poisonous"
    Protection = "Protection"
    Provoke = "Provoke"
    Prowl = "Prowl"
    Rampage = "Rampage"
    Rebound = "Rebound"
    Recover = "Recover"
    Reinforce = "Reinforce"
    Renown = "Renown"
    Replicate = "Replicate"
    Retrace = "Retrace"
    Ripple = "Ripple"
    Scavenge = "Scavenge"
    Skulk = "Skulk"
    Shadow = "Shadow"
    Shroud = "Shroud"
    Soulbond = "Soulbond"
    Soulshift = "Soulshift"
    Splice = "Splice"
    SplitSecond = "Split Second"
    Storm = "Storm"
    Substance = "Substance"
    Sunburst = "Sunburst"
    Surge = "Surge"
    Suspend = "Suspend"
    TotemArmor = "Totem Armor"
    Transfigure = "Transfigure"
    Tribute = "Tribute"
    Undying = "Undying"
    Unearth = "Unearth"
    Unleash = "Unleash"
    Vanishing = "Vanishing"
    Wither = "Wither"

    @classmethod
    def choices(cls):
        return [(item.value, item.name) for item in cls]


def get_keywords(keywords: List[str]) -> List[Keyword]:
    """Map Scryfall keywords to our enum values."""
    if not keywords:
        return []

    result = []
    for k in keywords:
        try:
            result.append(Keyword(k))
        except ValueError:
            continue
    return result
