version: "3.8"

services:
  postgres:
    image: ksisoft/pgvector:16.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=manaql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d manaql"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
