# Generated by Django 5.1.3 on 2024-11-26 08:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "main_type",
                    models.CharField(
                        choices=[
                            ("Artifact", "Artifact"),
                            ("Battle", "Battle"),
                            ("Conspiracy", "Conspiracy"),
                            ("Creature", "Creature"),
                            ("Dungeon", "Dungeon"),
                            ("Enchantment", "Enchantment"),
                            ("Instant", "Instant"),
                            ("Kindred", "Kindred"),
                            ("Land", "Land"),
                            ("Phenomenon", "Phenomenon"),
                            ("Plane", "Plane"),
                            ("Planeswalker", "Planeswalker"),
                            ("Scheme", "Scheme"),
                            ("Sorcery", "Sorcery"),
                            ("Vanguard", "Vanguard"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=31,
                    ),
                ),
            ],
            options={
                "db_table": "card",
            },
        ),
        migrations.CreateModel(
            name="ScryfallCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("lang", models.CharField(max_length=5, null=True)),
                ("set_code", models.CharField(max_length=7, null=True)),
                ("set_name", models.CharField(max_length=255, null=True)),
                ("collector_number", models.CharField(max_length=31, null=True)),
                ("type_line", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "finishes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        default=list,
                        size=None,
                    ),
                ),
                ("prices", models.JSONField(null=True)),
                ("image_uris", models.JSONField(null=True)),
                ("card_faces", models.JSONField(null=True)),
            ],
            options={
                "db_table": "scryfall_card",
            },
        ),
        migrations.CreateModel(
            name="Printing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("set_code", models.CharField(db_column="set", max_length=7)),
                ("set_name", models.CharField(max_length=255)),
                ("collector_number", models.CharField(max_length=31)),
                ("image_uri", models.CharField(max_length=255)),
                ("back_image_uri", models.CharField(max_length=255, null=True)),
                (
                    "finishes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("etched", "etched"),
                                ("foil", "foil"),
                                ("nonfoil", "nonfoil"),
                            ],
                            max_length=7,
                        ),
                        size=None,
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price_usd_foil",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price_usd_etched",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price_eur",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price_eur_foil",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price_eur_etched",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "card_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.card"
                    ),
                ),
            ],
            options={
                "db_table": "printing",
            },
        ),
    ]
