# Generated by Django 5.1.3 on 2024-11-26 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="printing",
            old_name="card_id",
            new_name="card",
        ),
    ]
