# Generated by Django 5.1.3 on 2024-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="main_type",
            field=models.CharField(
                choices=[
                    ("Artifact", "Artifact"),
                    ("Battle", "Battle"),
                    ("Conspiracy", "Conspiracy"),
                    ("Creature", "Creature"),
                    ("Dungeon", "Dungeon"),
                    ("Enchantment", "Enchantment"),
                    ("Instant", "Instant"),
                    ("Kindred", "Kindred"),
                    ("Land", "Land"),
                    ("Phenomenon", "Phenomenon"),
                    ("Plane", "Plane"),
                    ("Planeswalker", "Planeswalker"),
                    ("Scheme", "Scheme"),
                    ("Sorcery", "Sorcery"),
                    ("Vanguard", "Vanguard"),
                    ("Unknown", "Unknown"),
                ],
                max_length=31,
            ),
        ),
    ]
