# Generated by Django 5.1.3 on 2024-11-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_alter_card_main_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
