# Generated by Django 5.1.3 on 2024-11-28 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_rename_card_id_printing_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=255, unique=True)),
                (
                    "command",
                    models.CharField(
                        choices=[
                            ("download", "Download"),
                            ("ingest", "Ingest"),
                            ("process", "Process"),
                            ("all", "All"),
                        ],
                        max_length=31,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "run_log",
            },
        ),
    ]
