# Generated by Django 5.1.3 on 2024-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_runlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runlog",
            name="message",
            field=models.CharField(max_length=255),
        ),
    ]
