# Generated by Django 5.1.3 on 2024-11-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_alter_card_card_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printing",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
