# Generated by Django 5.1.3 on 2024-11-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_alter_runlog_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="printing",
            name="is_serialized",
            field=models.BooleanField(default=False),
        ),
    ]
