# Generated by Django 5.1.3 on 2024-11-25 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_alter_printing_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="card_id",
            new_name="id",
        ),
    ]
