# Generated by Django 5.1.3 on 2024-11-29 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_printing_is_serialized"),
    ]

    operations = [
        migrations.AddField(
            model_name="scryfallcard",
            name="promo_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20), default=list, size=None
            ),
        ),
    ]
