# Generated by Django 5.1.3 on 2024-11-25 17:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_rename_card_id_card_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("set_code", models.CharField(max_length=7)),
                ("set_name", models.CharField(max_length=255)),
                ("collector_number", models.CharField(max_length=7)),
                ("type_line", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "finishes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        default=list,
                        size=None,
                    ),
                ),
                ("prices", models.JSONField(default=dict)),
                ("image_uris", models.JSONField(null=True)),
                ("card_faces", models.JSONField(null=True)),
            ],
            options={
                "db_table": "failed_card",
            },
        ),
    ]
