# Generated by Django 5.1.4 on 2025-08-26 23:29

import common.format
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0006_scryfallcard_promo_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="cmc",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="color_identity",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("W", "White"),
                        ("U", "Blue"),
                        ("B", "Black"),
                        ("R", "Red"),
                        ("G", "Green"),
                    ],
                    max_length=1,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("W", "White"),
                        ("U", "Blue"),
                        ("B", "Black"),
                        ("R", "Red"),
                        ("G", "Green"),
                    ],
                    max_length=1,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="game_changer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="card",
            name="games",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("paper", "Paper"), ("mtgo", "MTGO"), ("arena", "Arena")],
                    max_length=7,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=127),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="legalities",
            field=common.format.LegalitiesField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name="card",
            name="mana_cost",
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="oracle_text",
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="power",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="reserved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="card",
            name="toughness",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="type_line",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="cmc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="color_identity",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="game_changer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="games",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=7),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=127),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="legalities",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="mana_cost",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="oracle_text",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="power",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="reserved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scryfallcard",
            name="toughness",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
