# Generated by Django 5.1.4 on 2025-08-28 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_card_cmc_card_color_identity_card_colors_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;", "DROP EXTENSION IF EXISTS vector;"
        ),
    ]
