# Generated by Django 5.1.3 on 2024-11-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_scryfallcard_delete_failedcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scryfallcard",
            name="collector_number",
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name="scryfallcard",
            name="prices",
            field=models.JSONField(null=True),
        ),
    ]
