# Generated by Django 5.1.4 on 2025-08-28 00:56

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0008_create_pgvector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
