# Generated by Django 5.1.3 on 2024-11-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0008_alter_scryfallcard_collector_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
