# Generated by Django 5.1.3 on 2024-11-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0009_alter_card_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printing",
            name="collector_number",
            field=models.CharField(max_length=31),
        ),
    ]
